version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  database:
    image: postgres:14-alpine
    container_name: closer_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-closer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-closer123}
      POSTGRES_DB: ${POSTGRES_DB:-closerdb}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - closer_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U closer -d closerdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da API (Backend)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: closer_backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-3244}:3244"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-closer}:${POSTGRES_PASSWORD:-closer123}@database:5432/${POSTGRES_DB:-closerdb}"
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  # Serviço da Aplicação (Frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: closer_frontend
    ports:
      - "${FRONTEND_PORT:-3007}:3007"
    environment:
      - VITE_API_BASE_URL=http://localhost:3244
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  closer_db_data:
    driver: local 