version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: closer-postgres
    environment:
      POSTGRES_USER: closer
      POSTGRES_PASSWORD: closer123
      POSTGRES_DB: closer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
