export enum EServiceType {
  ACOMPANHAMENTO = 'ACOMPANHAMENTO',
  ANIVERSARIO = 'ANIVERSARIO',
  BOOK = 'BOOK',
  CASAL = 'CASAL',
  CASAMENTO = 'CASAMENTO',
  DIA_DAS_MAES = 'DIA_DAS_MAES',
  ENSAIO_FAMILIA = 'ENSAIO_FAMILIA',
  ENSAIO_FEMININO = 'ENSAIO_FEMININO',
  ENSAIO_GESTANTE = 'ENSAIO_GESTANTE',
  ENSAIO_INFANTIL = 'ENSAIO_INFANTIL',
  EVENTO = 'EVENTO',
  FORMATURA = 'FORMATURA',
  INSTITUCIONAL = 'INSTITUCIONAL',
  MEMORIAS_POLAROID = 'MEMORIAS_POLAROID',
  NEWBORN = 'NEWBORN',
  PARTO = 'PARTO',
  SMASH_THE_CAKE = 'SMASH_THE_CAKE'
} 